### ISSUE TITLE
Guys, there is SolidJS

### ISSUE THREAD

**Issue by elite174** [recksjs/recks#20]
There is already reactive framework :)

https://www.solidjs.com/

**Comment by gustavostuff** [comment]
They don't do the same, right? maybe I'm missing something.

**Comment by jorroll** [comment]
Poorly done @elite174. Obviously you are correct. Solidjs does exist (and I also love it). And before solidjs there was (and is)  [cycle.js](https://cycle.js.org/). At surface level, you're making a factual statement that solidjs exists which is like...ok. If you're implying that _there should be only one reactive framework_...well, bluntly put, that's a bad idea for (hopefully) obvious reasons. And, if that were true, solidjs itself wouldn't exist (again -> there was cycle.js and probably others).

On just a technical level, solidjs uses signals for its reactivity while recks uses rxjs observables. If recks was at a fleshed out 1.0 stage, I expect many rxjs lovers would prefer the reck's approach to reactivity of the solidjs approach.

This being said, to the extent you are (clumsily) tying to say that solidjs achieves many of the same goals as recks and is father along in development (so users of recks might want to be aware of it), I agree. Personally, as a longtime "watcher" of the recks library, solidjs has achieved everything I was looking for and I would recommend anyone interested in recks take a serious look at solidjs. While I would like to be able to embed observable values directly in jsx (a goal of recks), I'm fully content with using solidjs's "signal" abstraction. Notably, users can _very easily_ convert a signal to an rxjs observable ([see solidjs docs](https://www.solidjs.com/docs/latest/api#observable)) and back again ([docs](https://www.solidjs.com/docs/latest/api#from)) like the following:

```ts
import { observable, from as obsToSignal } from 'solid-js';
import { from } from 'rxjs';

const [myNumber, setMyNumber] = createSignal(0);

const obsv$ = from(observable(myNumber));
const myNumberAgain = obsToSignal(obsv$);
```

And, like recks, solidjs component functions are only called once (which contrasts with React which renders components on every change).

This being said, I imagine recks _was_ (since it's not actively developed) a passion (and learning) project for the developer in addition to anything else. The existence of another, similar project doesn't necessarily change the developer's motivations for working on recks (nor should it).

**Comment by elite174** [comment]
Well, a framework built on top of rxjs has a limited usage (for people who loves rxjs). Eventually, you'll abandon (wow, already) this project (because it takes a lot time to make working and stable solution which faces users needs), so it's better from my point of view to start developing something else (new and unique). It will save a lot of time and efforts.

**Comment by kosich** [comment]
@jorroll , thank you for putting it so nicely! ❤️

This is still an experiment and a work of passion. At least currently, it is not intended to be used as a framework for a serious project, rather to be played with for exploring reactive streams ideas.

This project gave birth to other experiments like [rxjs-autorun](https://github.com/kosich/rxjs-autorun) and [rxjs-proxify](https://github.com/kosich/rxjs-proxify). Also I got to meet a lot of amazing people through this project! _(including Ryan Carniato, SolidJS author)_

So, I think this is a fun project and I never regretted working on it 🙌
